### ISSUE TITLE
How are these files generated?

### ISSUE THREAD

**Issue by kafran** [msperlin/GetITRData_auxiliary#1]
I see GetITRData has a strong dependency for these files. How are these files generated?

**Comment by msperlin** [comment]
I generate them in my home computer, fecthing and organizing data from B3.

**Comment by msperlin** [comment]
This way I can make sure new data from new income statements or new companies are available to the user.

**Comment by kafran** [comment]
Do you do it manually?

Professor Perlin, doesn't CVM publishes the financials statements in XBRL?

**Comment by msperlin** [comment]
Kind of. I have a R script that does all the heavy work.

Its does, but its not organized as the zip files in B3.

**Comment by kafran** [comment]
> Kind of. I have a R script that does all the heavy work.

Publish it here =)

> Its does, but its not organized as the zip files in B3.

Do you know where these files are?

**Comment by msperlin** [comment]
Maybe. I need to clean it up  bit.

They are available in the "download files" section of each company.
